### ISSUE TITLE
CBW won't open in borderless windows

### ISSUE THREAD

**Issue by epopcop** [PlGGS/Cemu-Borderless-Window#1]
AGAIN, Thanks dude!

So, I'm using this command:
`.\CBW.exe -bw true -cemu ".\Cemu-BOTW.lnk"`
(The lnk is to the `-g`.)
This opens CBW with the option "boarderless window" ticked, hides the taskbar, opens cemu and start loading the game. But it won't change anything in cemu.

With v1 of CBW, I had to add to my startup script the `timeout` command. If i didn't, CBW wouldn't recognize cemu because CBW lunches quicker. 
With v1.1, as you can see everything seems working, but I can see the CBW window before cemu window actually opens. that why I think this problem is related.

:)

**Comment by PlGGS** [comment]
Next update incoming.
